# Generated by Django 5.0.6 on 2026-05-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0002_producto_barcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_bodega', to='productos.producto')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Stock por bodega',
                'verbose_name_plural': 'Stock por bodegas',
                'ordering': ['producto__nombre'],
                'unique_together': {('sede', 'producto')},
            },
        ),
    ]
