# Generated by Django 5.0.6 on 2026-05-17 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_stockbodega'),
        ('productos', '0004_producto_es_insumo_producto_receta_servicio_combo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrasladoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_traslado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_traslado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('REALIZADO', 'Realizado'), ('ANULADO', 'Anulado')], default='REALIZADO', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sede_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='inventario.sede')),
                ('sede_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='inventario.sede')),
            ],
            options={
                'verbose_name': 'Traslado entre bodega',
                'verbose_name_plural': 'Traslados entre bodegas',
                'ordering': ['-created'],
            },
        ),
    ]
