# Generated by Django 5.0.6 on 2026-05-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='created',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('YAPE', 'YAPE'), ('PLIN', 'PLIN'), ('TARJETA', 'TARJETA')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
