# Generated by Django 5.0.6 on 2026-05-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_options_rename_fecha_venta_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PAGADA', 'Pagada'), ('ESPERA', 'Espera'), ('ANULADA', 'Anulada')], default='PAGADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
