# Generated by Django 5.0.6 on 2026-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_loginattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='updated',
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
