# Generated by Django 5.0.6 on 2026-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_insumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='receta_servicio_combo',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('RECETA', 'RECETA'), ('SERVICIO', 'SERVICIO'), ('COMBO', 'COMBO')], default='NINGUNO', max_length=20),
        ),
    ]
