# Generated by Django 5.0.6 on 2026-05-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('SD', 'Sin documento'), ('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet Extranjería')], default='SD', max_length=10),
        ),
    ]
