# Generated by Django 5.0.6 on 2026-05-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='cantidad_devuelta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
