# Generated by Django 5.0.6 on 2026-05-19 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_detallecompra_cantidad_devuelta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(default='PROCESADA', max_length=20)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='compras.compra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.proveedor')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución de compra',
                'verbose_name_plural': 'Devoluciones de compras',
                'ordering': ['-fecha'],
            },
        ),
    ]
