# Generated by Django 5.0.6 on 2026-05-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_devolucioncompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], default='EFECTIVO', max_length=30),
        ),
        migrations.AddField(
            model_name='compra',
            name='salio_caja',
            field=models.BooleanField(default=True),
        ),
    ]
