# Generated by Django 5.0.6 on 2026-05-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_devolucioncompra'),
        ('gastos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sacar_caja', models.BooleanField(default=False)),
                ('estado', models.CharField(default='PROCESADO', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.categoriagasto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.proveedor')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
