# Generated by Django 5.0.6 on 2026-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_alter_gasto_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='es_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha_aplicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagar_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='sacar_caja_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_gasto',
            field=models.CharField(default='CONTADO', max_length=20),
        ),
    ]
